name = "un-gomoku-ws"
main = "apps/server/worker.ts"
compatibility_date = "2026-02-24"

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoomDurableObject" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameServerDurableObject"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["GameRoomDurableObject"]
deleted_classes = ["GameServerDurableObject"]
