"""Python port of the authoritative TypeScript game rules (packages/core).

The TS implementation is the source of truth. Parity is enforced by
tests/test_rules_parity.py, which replays vectors generated by
tools/parity-arena/src/generate-vectors.ts (run `bun run gen:parity`).
"""

from ungomoku_ml.rules.board import (
    EMPTY,
    PLAYER1,
    PLAYER2,
    board_from_string,
    board_to_string,
    new_board,
    other_player,
)
from ungomoku_ml.rules.constants import (
    BOARD_SIZE,
    MAX_CANDIDATES,
    SUCCESS_PROBABILITY,
    WIN_LENGTH,
)
from ungomoku_ml.rules.turn import TurnOutcome, calculate_success, resolve_turn
from ungomoku_ml.rules.validation import validate_candidates
from ungomoku_ml.rules.win import check_win_at, is_board_full

__all__ = [
    "BOARD_SIZE",
    "EMPTY",
    "MAX_CANDIDATES",
    "PLAYER1",
    "PLAYER2",
    "SUCCESS_PROBABILITY",
    "WIN_LENGTH",
    "TurnOutcome",
    "board_from_string",
    "board_to_string",
    "calculate_success",
    "check_win_at",
    "is_board_full",
    "new_board",
    "other_player",
    "resolve_turn",
    "validate_candidates",
]
