"""Replays TS-generated vectors through the Python rules port.

Fixture: tests/fixtures/rule-vectors.json, generated by
`bun run gen:parity` (tools/parity-arena/src/generate-vectors.ts).
Every random value the TS resolveTurn consumed is recorded, so outcomes must
match exactly — including strict `<` probability checks and floor-based
candidate index selection.
"""

import json
from pathlib import Path

import pytest

from ungomoku_ml.rules import (
    BOARD_SIZE,
    MAX_CANDIDATES,
    PLAYER1,
    PLAYER2,
    SUCCESS_PROBABILITY,
    WIN_LENGTH,
    board_from_string,
    board_to_string,
    new_board,
    resolve_turn,
    validate_candidates,
)

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "rule-vectors.json"

PLAYER_IDS = {"player1": PLAYER1, "player2": PLAYER2}
WINNER_IDS = {"player1": PLAYER1, "player2": PLAYER2, None: 0}


def load_fixture() -> dict:
    if not FIXTURE_PATH.exists():
        pytest.fail(f"missing fixture {FIXTURE_PATH}; run `bun run gen:parity` from the repo root")
    with FIXTURE_PATH.open(encoding="utf-8") as f:
        return json.load(f)


FIXTURE = load_fixture()


def test_constants_match_fixture_meta() -> None:
    meta = FIXTURE["meta"]
    assert meta["boardSize"] == BOARD_SIZE
    assert meta["winLength"] == WIN_LENGTH
    assert meta["maxCandidates"] == MAX_CANDIDATES
    assert {int(k): v for k, v in meta["successProbability"].items()} == SUCCESS_PROBABILITY


@pytest.mark.parametrize("game", FIXTURE["games"], ids=lambda g: g["name"])
def test_game_replay(game: dict) -> None:
    board = board_from_string(game["initialBoard"]) if "initialBoard" in game else new_board()

    for turn_index, turn in enumerate(game["turns"]):
        player = PLAYER_IDS[turn["player"]]
        candidates = [tuple(c) for c in turn["candidates"]]
        randoms = iter(turn["randoms"])

        assert validate_candidates(board, candidates) is None, (
            f"turn {turn_index}: candidates failed validation"
        )

        outcome = resolve_turn(board, player, candidates, lambda r=randoms: next(r))
        expected = turn["expected"]

        context = f"{game['name']} turn {turn_index}"
        assert outcome.success == expected["success"], context
        expected_placed = tuple(expected["placed"]) if expected["placed"] else None
        assert outcome.placed == expected_placed, context
        assert outcome.game_over == expected["gameOver"], context
        assert outcome.winner == WINNER_IDS[expected["winner"]], context
        assert outcome.is_draw == expected["isDraw"], context
        assert next(randoms, None) is None, f"{context}: unconsumed random values"

    assert board_to_string(board) == game["finalBoard"], game["name"]


@pytest.mark.parametrize("case", FIXTURE["validationCases"], ids=lambda c: c["name"])
def test_validation_case(case: dict) -> None:
    board = board_from_string(case["board"])
    candidates = [tuple(c) for c in case["candidates"]]
    error = validate_candidates(board, candidates)
    if case["expected"]["ok"]:
        assert error is None
    else:
        assert error == case["expected"]["error"]
